### ISSUE TITLE
直接用ios7之后的NSURLSessionDownloadTask实现下载比较好吧

### ISSUE THREAD

**Issue by Rakutou** [DeveloperLx/Troubles-of-realizing-download-module#2]
不过用NSURLSessionDownloadTask坑不不少啊,特别是断点续传

**Comment by DeveloperLx** [comment]
用NSURLSessionDownloadTask能断点续传么？你有没发现下了一半把App一关，再打开应用就没辙了？

**Comment by youngshook** [comment]
NSURLSessionDownloadTask 实现断点续传还是很方便的吧，文档提供的接口还是很丰富的。
检测到App 在关闭通知消息的时候，可以保存下 resumeData，重新打开应用的时候 Resume 即可。

**Comment by DeveloperLx** [comment]
你实操地试试看，resumeData未必是你想象中的那个东西

**Comment by youngshook** [comment]
实操没问题, 不知resume 背了什么锅...
