### ISSUE TITLE
对操作的理解

### ISSUE THREAD

**Issue by seedante** [DeveloperLx/Troubles-of-realizing-download-module#3]
看了前后两篇文章，我对网络不熟，仅就这篇文章里关于 operation 和 queue 的观点讨论下：

> 惊人事实 1： 对queue中前一个下载operation执行pause方法，下一个operation并不能自动启动进入正在执行的状态！！
> 
> 惊人事实 2： 如果queue中前一个下载operation执行失败了（可用下载中途断网进行模拟），它将从queue中自动地被移除掉！！
> 
> 惊人事实 3： 注意到代码里那个failure回调的block了没？它不仅仅将在operation执行失败的时候被调用，还会在operation被cancel的时候被调用！！所以对于神马叫做“operation的失败”，你要重新建立起你的世界观了！！
> 
> 惊人事实 4： 如果对一个正处于pause状态的operation执行cancel会怎么样？答案是这个operation还保留在queue中！！并且仍然保持着pause状态！！仅有的一点变化，是它的isCancelled属性，变成了YES！！

一个 operation 加入 queue后，queue 只对 operation 的`finished`属性做出响应，一旦`finished`为`true`了，在 queue 眼里，这个 operation 就结束了，会尽快移除，至于 operation 中执行的任务是否成功 queue 并不关心。而对 operation 而言，`finished`属性为`true`后，它自身也认为任务结束，至于任务是否成功，那是开发者关心的事，如果提供了`completionBlock`，会执行这个 block。

大家知道 NSOperation 本身并没有 pause, resume 的功能，`AFHTTPRequestOperation`以及它的父类`AFURLConnectionOperation`添加了这两个功能，但并未对`finished`属性做出修改，所以，以上的惊人事实并不是 queue 该背的锅。以下为解释：

惊人事实1：为何下一个 operation 没有自动启动，因为前一个 operation 还不是`isFinished`, queue 仍然在维持前面一个 operation 的执行。

惊人事实2：执行失败后，`AFURLConnectionOperation`最终发出了`isFinished`的 KVO 通知，按照我上面说的，queue 认为这个 operation 结束了，会移除这个 operation。

惊人事实3：只要`finished`为`true`后，completionBlock 就会执行，cancel 一个 operation 也会修改`finished`为`true`，而`AFHTTPRequestOperation`的实现里，failure 的 block 加入了 completionBlock，所以这个事实就发生了。

惊人事实4：只要 operation 的`finished`还是`false`，它就会留在 queue 里。但是代码里调用 cancel()方法
最终修改了`finished`属性，这点存疑。

因此，惊人事实7是前面4个惊人事实的根本原因。

对于后面的5和6，我的测试是只要是添加到 queue 的 operation，无论是否已经开始执行，直接调用 `start()`方法会抛出异常。测试环境是 iOS 8.x 和 iOS9.x 的模拟器以及 iOS9.3的真机+ Xcode 7 以及 Swift 2.2，所以对5和6表示不解。

**Comment by DeveloperLx** [comment]
我没有看懂，我的文章中从未讲过queue该背锅啊？我所讲到的所有现象只是说实际使用AFHTTPRequestOperation进行下载操作时，会与我们直观上预想的有所差别，所以一定要以实践为准避免这些坑。
我看了你所写的，应该都是对于发生我所说现象原因的一个分析。首先非常感谢你的用心，但实在地讲，我当时写这篇文章时都已想到了这些，只是我所写的侧重点不在这里，而是在于现象，在于避免的方法，所以并未写出来。你说我“对 queue 和 operation 的理解有偏差”，可是我并未看出你跟我对它们认识上的差别，还请仔细斟酌。
最后一段我觉得还是比较有价值的。我这篇博写于将近一年之前，当时并未出现过抛出异常的现象，不清楚现在是什么样的情况了，我没有试过。欢迎你把自己测试、思考、分析和解决的方法分享给大家，我也愿成为其中一员虚心地学习请教

**Comment by seedante** [comment]
了解了，主要是我认为这样写没有明确指出发生这些现象的原因，容易让人对 queue 和 operation 的使用产生误解，尽管你的出发点是带出第二篇文章。

**Comment by DeveloperLx** [comment]
不要妄下判断啊，我可从来没讲过出发点是带出第二篇文章😂

**Comment by seedante** [comment]
额，你第二篇文章自己说抛砖引玉的啊。

**Comment by DeveloperLx** [comment]
你还是没看懂文章啊，我说的抛砖引玉说的是希望大神能来给出或封装一套更好的，坑少些的方案来解决下载管理的问题，从来没讲过是引出自己的第二篇文章，这个联想实在是跑得太偏了啊😂

**Comment by seedante** [comment]
好吧，不争执这点了。从微博对这篇文章的评论来看，大家是容易产生你对此理解不太对的印象。现在看来，只是你写文章的侧重点不一样罢了。关于第5和6点，我只是测试了普通的 operation 在 queue 里的表现，由于 AFNetwork 的实现是自己管理线程，不知道是不是这个的原因。
